<a href="https://colab.research.google.com/github/damnhuquynhvn-oss/thuchanhdeeplearning/blob/main/Lab01_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
#Array 1 chiều
my_list = [1, 9, 15, 39]

numpy_array = np.array(my_list)

print("Python list:", my_list)
print("Numpy array:", numpy_array)

print("Shape:", numpy_array.shape)
print("Dtype:", numpy_array.dtype)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
Shape: (4,)
Dtype: int64


In [3]:
#Array 2 chiều
c = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(c)
print("Shape:", c.shape)
print("Dtype:", c.dtype)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dtype: int64


In [4]:
#Array 3 chiều
d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print(d)
print("Shape:", d.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


In [5]:
#Tạo ma trận toàn số 0 và số 1
zero_matrix = np.zeros((2, 3))
one_matrix = np.ones((3, 3))

print("Zero matrix:")
print(zero_matrix)

print("\nOne matrix:")
print(one_matrix)

Zero matrix:
[[0. 0. 0.]
 [0. 0. 0.]]

One matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
#Reshape ma trận
e = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Original:")
print(e)
print(e.shape)

f = e.reshape(3, 2)

print("\nReshape (3,2)")
print(f)
print(f.shape)

Original:
[[1 2 3]
 [4 5 6]]
(2, 3)

Reshape (3,2)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [7]:
#Reshape nhiều kích thước khác
g = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

print(g)
print(g.shape)

h = g.reshape(3,4)
print("\nReshape (3,4)")
print(h)

j = g.reshape(3,2,2)
print("\nReshape (3,2,2)")
print(j)

k = g.reshape(2,3,2)
print("\nReshape (2,3,2)")
print(k)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)

Reshape (3,4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshape (3,2,2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]

Reshape (2,3,2)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#Flatten
g = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

flat = g.flatten()

print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
#hstack và vstack
f = np.array([1,2,3])
g = np.array([4,5,6])

h_stack = np.hstack((f,g))
v_stack = np.vstack((f,g))

print("Horizontal Append:")
print(h_stack)

print("\nVertical Append:")
print(v_stack)

Horizontal Append:
[1 2 3 4 5 6]

Vertical Append:
[[1 2 3]
 [4 5 6]]


In [10]:
#Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(100, size=(5,))
b = np.random.randint(100, size=(3,4))
c = np.random.randint(100, size=(3,4,3))

print("Random 1D:")
print(a)

print("\nRandom 2D:")
print(b)

print("\nRandom 3D:")
print(c)

Random 1D:
[69 76  7 63 23]

Random 2D:
[[60 37 59  2]
 [56 78 53 11]
 [63 48 24 66]]

Random 3D:
[[[88 98 42]
  [ 6 27 21]
  [29  9 13]
  [15 19  3]]

 [[91 52 42]
  [15 29 13]
  [58 96 44]
  [17  7 65]]

 [[37 86 25]
  [25 75 54]
  [99 90 91]
  [94 96 30]]]


In [11]:
#Sinh số thực ngẫu nhiên [0,1]
a = np.random.rand(5)

b = np.random.rand(3,4)

c = np.random.rand(3,4,3)

print("Random 1D:")
print(a)

print("\nRandom 2D:")
print(b)

print("\nRandom 3D:")
print(c)

Random 1D:
[0.4998882  0.80070368 0.42752953 0.41577094 0.23408984]

Random 2D:
[[0.77450191 0.64873949 0.95352035 0.5284464 ]
 [0.18638275 0.97963335 0.25387562 0.88268729]
 [0.62450109 0.7770191  0.90328568 0.97755053]]

Random 3D:
[[[0.01792283 0.73825394 0.34620723]
  [0.87600424 0.54020322 0.26696503]
  [0.96763193 0.50269268 0.36454075]
  [0.04804455 0.49617631 0.54893343]]

 [[0.04647956 0.25879274 0.18036242]
  [0.96157406 0.27675613 0.82294323]
  [0.35123195 0.55985209 0.68690237]
  [0.08733792 0.22541112 0.15002693]]

 [[0.24645892 0.76394008 0.03062371]
  [0.60597735 0.46066455 0.70275872]
  [0.27102356 0.51211818 0.7594737 ]
  [0.92796981 0.26171816 0.59488996]]]


In [12]:
#Phân phối chuẩn Gaussian
a = np.random.normal(loc=5, scale=0.5, size=10)

print(a)

[5.33541424 5.02671049 4.9568111  4.52227692 5.96999884 5.16968198
 5.29848362 5.20709198 4.80488278 4.57214694]


In [13]:
#Random từ tập giá trị cho trước
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])

print("One value:")
print(a)

b = np.random.choice(
    [2,4,6,8,10,12,14,16,18,20],
    size=(3,5)
)

print("\nMatrix:")
print(b)

One value:
20

Matrix:
[[ 4  2 18 12 20]
 [16  6 12 12 14]
 [ 2 20 10  6  8]]


In [14]:
#Thay đổi giá trị ma trận
A = np.ones((5,5))

print("Original:")
print(A)

A[2] = 2

print("\nChange third row:")
print(A)

A[:,2] = 3

print("\nChange third column:")
print(A)

Original:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Change third row:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Change third column:
[[1. 1. 3. 1. 1.]
 [1. 1. 3. 1. 1.]
 [2. 2. 3. 2. 2.]
 [1. 1. 3. 1. 1.]
 [1. 1. 3. 1. 1.]]


In [15]:
#arange
a = np.arange(1,20)

b = np.arange(1,20,2)

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [16]:
#linspace
a = np.linspace(1,5,num=10)

print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [17]:
#Index và Slice
a = np.array([
    [1,2,3],
    [4,5,6]
])

print(a)

print("First row:")
print(a[0])

print("Second row:")
print(a[1])

print("Second column:")
print(a[:,1])

print("First column:")
print(a[:,0])

print("First two values of second row:")
print(a[1,:2])

[[1 2 3]
 [4 5 6]]
First row:
[1 2 3]
Second row:
[4 5 6]
Second column:
[2 5]
First column:
[1 4]
First two values of second row:
[4 5]


In [18]:
#Series cơ bản
a = pd.Series([1,2,3])

print(a)

print("First value:")
print(a[0])

b = pd.Series(
    [1,2,3],
    index=["a","b","c"]
)

print(b)

print("First value:")
print(b["a"])

0    1
1    2
2    3
dtype: int64
First value:
1
a    1
b    2
c    3
dtype: int64
First value:
1


In [19]:
#Series từ Dictionary
calories = {
    "day1":420,
    "day2":380,
    "day3":390
}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [20]:
#Chuyển Numpy sang Pandas và ngược lại
h = np.array([
    [1,2],
    [3,4]
])

df_h = pd.DataFrame(h)

print("DataFrame:")
print(df_h)

numpy_h = np.array(df_h)

print("\nNumpy:")
print(numpy_h)

DataFrame:
   0  1
0  1  2
1  3  4

Numpy:
[[1 2]
 [3 4]]


In [21]:
#DataFrame từ Dictionary
dic = {
    "Name":["John","Smith"],
    "Age":[30,40]
}

df_dic = pd.DataFrame(dic)

print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [22]:
#DataFrame ngẫu nhiên có tên cột
r = np.random.randn(20,4)

df = pd.DataFrame(
    r,
    columns=["so1","so2","so3","so4"]
)

print(df.head())

        so1       so2       so3       so4
0  0.473129 -0.293985 -1.177627  0.564685
1  0.515687 -0.793453 -0.578506  0.337022
2  0.343714 -2.087768 -0.329267 -0.424695
3 -0.018617 -1.168897 -1.426850 -1.281394
4 -0.249258  0.925079  0.968872 -0.336061


In [23]:
#Slice DataFrame
r = np.random.randn(20,4)

df = pd.DataFrame(
    r,
    columns=["so1","so2","so3","so4"]
)

print(df.head())

print("\nChọn 1 cột:")
print(df["so1"])

print("\nChọn nhiều dòng:")
print(df[:3])

print("\nChọn nhiều cột:")
print(df[["so1","so3"]])

print("\niloc:")
print(df.iloc[:3,:2])

        so1       so2       so3       so4
0 -0.478651 -0.151961  0.108660  0.843659
1 -0.816716 -0.795712  2.093090  1.344906
2  1.798648  0.004403 -1.619229  1.489325
3  0.856887  1.111369 -1.558432  0.669126
4 -1.252843 -1.126768 -0.224749  0.028753

Chọn 1 cột:
0    -0.478651
1    -0.816716
2     1.798648
3     0.856887
4    -1.252843
5     1.395816
6    -0.264117
7    -2.332336
8     1.101214
9     1.576828
10    1.275703
11    0.368105
12   -0.059659
13   -1.503818
14    0.586819
15    0.184736
16    0.112502
17   -0.247278
18    0.903731
19    2.072112
Name: so1, dtype: float64

Chọn nhiều dòng:
        so1       so2       so3       so4
0 -0.478651 -0.151961  0.108660  0.843659
1 -0.816716 -0.795712  2.093090  1.344906
2  1.798648  0.004403 -1.619229  1.489325

Chọn nhiều cột:
         so1       so3
0  -0.478651  0.108660
1  -0.816716  2.093090
2   1.798648 -1.619229
3   0.856887 -1.558432
4  -1.252843 -0.224749
5   1.395816 -0.068215
6  -0.264117 -0.132309
7  -2.332336 -0.289237

In [24]:
#Xóa cột
df = pd.DataFrame(
    np.random.randn(5,4),
    columns=["so1","so2","so3","so4"]
)

df.drop(columns=["so2","so4"], inplace=True)

print(df)

        so1       so3
0 -0.716664  1.493828
1  1.740210 -1.139108
2 -0.013673  0.698265
3 -0.387341 -0.259773
4 -0.474659  0.825936


In [25]:
#Nối DataFrame
df1 = pd.DataFrame({
    "Name":["John","Smith","Paul"],
    "Age":[25,30,50]
})

df2 = pd.DataFrame({
    "Name":["Adam","Smith"],
    "Age":[26,11]
})

df_concat = pd.concat([df1,df2])

print(df_concat)

    Name  Age
0   John   25
1  Smith   30
2   Paul   50
0   Adam   26
1  Smith   11


In [26]:
#Loại bỏ trùng lặp
df1 = pd.DataFrame({
    "Name":["John","Smith","Paul"],
    "Age":[25,30,50]
})

df2 = pd.DataFrame({
    "Name":["Adam","Smith"],
    "Age":[26,11]
})

df_concat = pd.concat([df1,df2])

print(
    df_concat.drop_duplicates("Name")
)

    Name  Age
0   John   25
1  Smith   30
2   Paul   50
0   Adam   26


In [27]:
#Sắp xếp DataFrame
df1 = pd.DataFrame({
    "Name":["John","Smith","Paul"],
    "Age":[25,30,50]
})

df2 = pd.DataFrame({
    "Name":["Adam","Smith"],
    "Age":[26,11]
})

df_concat = pd.concat([df1,df2])

print(
    df_concat.sort_values("Age")
)

    Name  Age
1  Smith   11
0   John   25
0   Adam   26
1  Smith   30
2   Paul   50


In [28]:
#Đổi tên cột
df1 = pd.DataFrame({
    "Name":["John","Smith","Paul"],
    "Age":[25,30,50]
})

df_rename = df1.rename(
    columns={
        "Name":"Surname",
        "Age":"Age_pu11"
    }
)

print(df_rename)

  Surname  Age_pu11
0    John        25
1   Smith        30
2    Paul        50


In [32]:
#Đọc CSV
import pandas as pd

df = pd.read_csv("Salary_Data.csv")
print(df.head())


   YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891


In [33]:
#GroupBy DataFrame
import pandas as pd

path = "Fish.csv"

df_csv = pd.read_csv(path)

print(df_csv.head())

print("\nMean:")
print(df_csv.groupby("Species").mean(numeric_only=True))

print("\nWeight mean:")
print(df_csv.groupby("Species")["Weight"].mean())

print("\nHeight max:")
print(df_csv.groupby("Species")["Height"].max())

  Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream     242     23.2     25.4     30.0   11.52   4.02
1   Bream     290     24.0     26.3     31.2   12.48   4.30
2   Perch     120     18.0     20.0     22.0    7.20   3.10
3   Perch     150     19.0     21.0     23.0    7.80   3.30
4    Pike     300     30.0     32.0     35.0    8.50   5.10

Mean:
         Weight  Length1  Length2  Length3  Height  Width
Species                                                  
Bream     266.0     23.6    25.85     30.6   12.00   4.16
Perch     135.0     18.5    20.50     22.5    7.50   3.20
Pike      325.0     31.0    33.00     36.0    8.75   5.20

Weight mean:
Species
Bream    266.0
Perch    135.0
Pike     325.0
Name: Weight, dtype: float64

Height max:
Species
Bream    12.48
Perch     7.80
Pike      9.00
Name: Height, dtype: float64
