<a href="https://colab.research.google.com/github/damnhuquynhvn-oss/thuchanhdeeplearning/blob/main/Lab01_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import tensorflow as tf
import numpy as np

print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


In [24]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)


In [25]:
rank_2_tensor = tf.constant([
    [1, 2],
    [3, 4],
    [5, 6]
], dtype=tf.float16)

print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [26]:
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],
     [5,6,7,8,9]],

    [[10,11,12,13,14],
     [15,16,17,18,19]],

    [[20,21,22,23,24],
     [25,26,27,28,29]]
])

print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [27]:
print(rank_3_tensor)

print("Shape:", rank_3_tensor.shape)
print("Dtype:", rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
Shape: (3, 2, 5)
Dtype: <dtype: 'int32'>


In [28]:
print(rank_3_tensor)

print("Shape:", rank_3_tensor.shape)
print("Dtype:", rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
Shape: (3, 2, 5)
Dtype: <dtype: 'int32'>


In [29]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3,3])
print(t_2_one)

t_3_one = tf.ones([3,3,5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [30]:
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3,3])
print(t_2_one)

t_3_one = tf.ones([3,3,5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [31]:
lin_tensor = tf.linspace(5.0, 20.0, 5)

print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [32]:
range_tensor = tf.range(3.0, 7.0, delta=0.5)

print(range_tensor)

range_tensor = tf.range(3.0, delta=0.5)

print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [33]:
range_tensor = tf.random.normal([5])

print(range_tensor)

range_tensor = tf.random.normal([3,3])

print(range_tensor)

tf.Tensor([-0.03316643 -0.62834114  1.9649874  -0.80895084 -0.64510506], shape=(5,), dtype=float32)
tf.Tensor(
[[-1.2733709  -0.6481208  -0.68986636]
 [ 1.0838529  -1.108149   -0.3821575 ]
 [ 0.5373034   0.34052896 -0.0374777 ]], shape=(3, 3), dtype=float32)


In [34]:
range_tensor = tf.random.truncated_normal([5])

print(range_tensor)

range_tensor = tf.random.truncated_normal([3,2])

print(range_tensor)

range_tensor = tf.random.truncated_normal([3,2,2])

print(range_tensor)

tf.Tensor([-0.3730526  -0.41540107 -1.9412367   0.16476417 -1.6736491 ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.02876879 -0.7050448 ]
 [ 0.69021124 -0.27492088]
 [-0.55442405 -0.22488661]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[-0.42317384  1.4821359 ]
  [ 0.47525963  1.2544689 ]]

 [[-0.02460182 -0.1009674 ]
  [-0.747217   -0.30956057]]

 [[ 1.0754032   0.91555774]
  [ 0.28085852 -0.09369023]]], shape=(3, 2, 2), dtype=float32)


In [35]:
range_tensor = tf.random.uniform([5],
                                 minval=10,
                                 maxval=20)

print(range_tensor)

range_tensor = tf.random.uniform([3,2],
                                 minval=10,
                                 maxval=20)

print(range_tensor)

range_tensor = tf.random.uniform([3,2,5],
                                 minval=10,
                                 maxval=20)

print(range_tensor)

tf.Tensor([11.4633255 16.597502  11.506552  19.881802  10.68475  ], shape=(5,), dtype=float32)
tf.Tensor(
[[15.371842 13.577394]
 [16.58413  14.461729]
 [14.256358 19.297878]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[19.721035 19.051622 17.861086 18.803741 13.250384]
  [13.959838 11.263277 13.185486 19.798851 17.160261]]

 [[15.246736 11.437807 13.948687 14.762324 14.192685]
  [11.975811 13.446679 10.91049  16.67573  17.742947]]

 [[15.365652 16.172443 18.397327 15.860407 15.25503 ]
  [18.259071 15.107496 16.950829 15.323285 16.34571 ]]], shape=(3, 2, 5), dtype=float32)


In [36]:
range_tensor = tf.random.uniform([5],
                                 minval=10,
                                 maxval=20)

print(range_tensor)

print(tf.random.shuffle(range_tensor))

tf.Tensor([13.849844 18.236504 19.719948 15.500458 11.4122  ], shape=(5,), dtype=float32)
tf.Tensor([18.236504 11.4122   13.849844 15.500458 19.719948], shape=(5,), dtype=float32)


In [37]:
tf_float = tf.constant(3.9, tf.float32)

print(tf_float)
print(tf_float.dtype)

tf_int = tf.cast(tf_float,
                 dtype=tf.int32)

print(tf_int)
print(tf_int.dtype)

tf.Tensor(3.9, shape=(), dtype=float32)
<dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32)
<dtype: 'int32'>


In [38]:
x = tf.constant(2, dtype=tf.float32)

print(tf.sqrt(x))

tf.Tensor(1.4142135, shape=(), dtype=float32)


In [39]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)

c = tf.add(a,b)

print(c)
print(c.numpy())

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
[[4 6]]


In [40]:
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)

c = tf.multiply(a,b)

print(c)
print(c.numpy())

tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
[[3 8]]


In [41]:
a = tf.constant([6.,6.,6.])
b = tf.constant([4.,4.,4.])
c1 = tf.constant([3.,3.,3.])

d = tf.add(a,b)
e = tf.add_n([a,b,c1])
f = tf.subtract(a,b)
g = tf.multiply(a,b)
h = tf.divide(a,b)

i = tf.scalar_mul(3,a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a,b)
l = tf.negative(a)

print("add:", d)
print("add_n:", e)
print("subtract:", f)
print("multiply:", g)
print("divide:", h)
print("scalar_mul:", i)
print("reciprocal:", j)
print("mod:", k)
print("negative:", l)

add: tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
add_n: tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)
subtract: tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
multiply: tf.Tensor([24. 24. 24.], shape=(3,), dtype=float32)
divide: tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float32)
scalar_mul: tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
reciprocal: tf.Tensor([0.16666667 0.16666667 0.16666667], shape=(3,), dtype=float32)
mod: tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
negative: tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


In [42]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print("round:", r1)
print("rint:", r2)
print("ceil:", r3)
print("floor:", r4)

round: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
rint: tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
ceil: tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
floor: tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


In [43]:
t1 = tf.constant([
    [4.,3.,2.],
    [3.,2.,1.]
])

t2 = tf.constant([
    [1.,2.],
    [3.,4.],
    [5.,6.]
])

dot_x = tf.tensordot(t1, t2, axes=1)

print(dot_x)

tf.Tensor(
[[23. 32.]
 [14. 20.]], shape=(2, 2), dtype=float32)


In [44]:
toan = tf.Variable(8.5, dtype=tf.float32)

print(toan)

diem = tf.Variable([5,9])

print(diem)

print("Shape:", diem.shape)
print("Type:", diem.dtype)
print("Numpy:", diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape: (2,)
Type: <dtype: 'int32'>
Numpy: [5 9]


In [45]:
toan = tf.Variable(8.5, dtype=tf.float32)

diem = tf.Variable([5,9])

print(diem)

diem.assign([8,10])

print(diem)

diem.assign_add([1,1])

print(diem)

diem.assign_sub([5,5])

print(diem)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


In [46]:
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

a_function_that_uses_a_graph = tf.function(
    a_regular_function
)

x1 = tf.constant([[1.0,2.0]])
y1 = tf.constant([[2.0],[3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1,y1,b1).numpy()

tf_function_value = a_function_that_uses_a_graph(
    x1,y1,b1
).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


In [47]:
def inner_function(x,y,b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0],[3.0]])
    b = tf.constant(4.0)

    return inner_function(x,y,b)

result = outer_function(
    tf.constant([[1.0,2.0]])
)

print(result.numpy())

[[12.]]


In [48]:
class SimpleModule(tf.Module):

    def __init__(self, name=None):
        super().__init__(name=name)

        self.a_variable = tf.Variable(5.0)

    def __call__(self, x):
        return self.a_variable * x


simple_module = SimpleModule()

print(simple_module(tf.constant(2.0)))

print("Variables:")
for var in simple_module.variables:
    print(var)

tf.Tensor(10.0, shape=(), dtype=float32)
Variables:
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>


In [49]:
class SimpleModule(tf.Module):

    def __init__(self, name=None):
        super().__init__(name=name)

        self.a_variable = tf.Variable(5.0)

    def __call__(self, x):
        return self.a_variable * x


simple_module = SimpleModule()

print(simple_module(tf.constant(2.0)))

print("Variables:")
for var in simple_module.variables:
    print(var)

tf.Tensor(10.0, shape=(), dtype=float32)
Variables:
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=5.0>


In [52]:
class Dense(tf.Module):

    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)

        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]),
            name='w'
        )

        self.b = tf.Variable(
            tf.zeros([out_features]),
            name='b'
        )

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)


class SequentialModule(tf.Module):

    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(3,3)
        self.dense_2 = Dense(3,2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)


my_model = SequentialModule()

print(
    my_model(
        tf.constant([[2.0,2.0,2.0]])
    )
)

chk_path = "./my_checkpoint"

checkpoint = tf.train.Checkpoint(
    model=my_model
)

checkpoint.write(chk_path)

print("Saved checkpoint")

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
Saved checkpoint


In [53]:
new_model = SequentialModule()

new_checkpoint = tf.train.Checkpoint(
    model=new_model
)

new_checkpoint.restore("./my_checkpoint")

print(
    new_model(
        tf.constant([[2.0,2.0,2.0]])
    )
)

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
